{{- if ((.Values).deployment).enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
{{- if not (.Values.autoscaling).enabled }}
  replicas: {{ default 1 .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  {{- end }}
  {{- if .Values.minReadySeconds }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.configMaps }}
        checksum/configmaps: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ default "false" .Values.automountServiceAccountToken }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- with .Values.extraInitContainers }}
      initContainers:
      {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository ( default "latest" .Values.image.tag ) }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.extraEnv }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          envFrom:
          {{- range .Values.envFromSecretNames }}
            - secretRef:
                name: {{ tpl . $ }}
          {{- end }}
          {{- range .Values.envFromConfigMapNames }}
            - configMapRef:
                name: {{ tpl . $ }}
          {{- end }}
          {{- if ( or ((.Values).service).port ((.Values).service).containerPort ) }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort | default .Values.service.port }}
              protocol: TCP
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if or .Values.extraVolumeMounts .Values.securityContext.readOnlyRootFilesystem }}
          volumeMounts:
          {{- if .Values.securityContext.readOnlyRootFilesystem }}
            - name: tmp
              mountPath: /tmp
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
            {{- tpl (toYaml .Values.extraVolumeMounts) . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.lifecycle }}
          lifecycle:
            {{- toYaml .Values.lifecycle | nindent 12 }}
          {{- end }}
        {{- with .Values.extraContainers }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ default "30" .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: tmp
          emptyDir: {}
      {{- end }}
      {{- if .Values.extraVolumes }}
        {{- tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}

      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}