{{- range $secret := .Values.externalSecrets }}
{{- $fullName := tpl $secret.name $ -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $secret.storeName | default "vault" }}
    kind: {{ $secret.storeKind | default "ClusterSecretStore" }}
  target:
    name: {{ $fullName }}
  dataFrom:
    - extract:
        key: {{ $secret.path | default (printf "apps/%s/%s/%s/%s" $.Values.clusterName $.Release.Namespace $.Release.Name $fullName) }}
{{- end }}
