{{- if ((.Values).service).enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
{{- with .Values.service.annotations }}
  annotations:
{{- tpl (toYaml .) $ | nindent 4 }}
{{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}